spring:
  application.name: pastebin
  mvc.hiddenmethod.filter.enabled: true
  data.redis.port: 6379
  profiles.active: local  # The local profile is used by default
server.port: 9090

---
# Local profile configuration
spring:
  config.activate.on-profile: local
  data.redis.host: localhost

---
# Docker profile configuration
spring:
  config.activate.on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres_db:5432/pastebin
    username: login
    password: password
  data.redis.host: redis
  boot:
    admin:
      client:
        enabled: true
        url: http://spring-boot-admin:8081

management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"